name: Build DW1560 BlueToolFixup

on:
  workflow_dispatch:

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    runs-on: macos-latest

    env:
      JOB_TYPE: BUILD

    steps:
      - name: Checkout experimental BrcmPatchRAM
        uses: actions/checkout@v4

      - name: Checkout MacKernelSDK
        uses: actions/checkout@v4
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1

      - name: Build Release
        run: |
          xcodebuild -jobs 1 -target Package -configuration Release

      - name: Show build output
        run: |
          find build -type f -name "*.zip" -print
          find build -type d -name "BlueToolFixup.kext" -print

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: DW1560-BrcmPatchRAM
          path: build/*/*/*.zip
